info:
  name: Create New Product
  type: http
  seq: 2

http:
  method: POST
  url: "{{BACKEND_URL}}/index.php?resource=inventory&apicall=insertData"
  params:
    - name: resource
      value: inventory
      type: query
    - name: apicall
      value: insertData
      type: query
  body:
    type: multipart-form
    data:
      - name: nama_produk
        type: text
        value: Pocari
      - name: harga
        type: text
        value: "7000"
      - name: stok
        type: text
        value: "10"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
