info:
  name: Create Product
  type: http
  seq: 2

http:
  method: POST
  url: "{{BACKEND_URL}}/index.php?resource=inventory&apicall=insertData"
  params:
    - name: resource
      value: inventory
      type: query
    - name: apicall
      value: insertData
      type: query
  body:
    type: json
    data: |-
      {
        "nama_produk": "isoplus",
        "harga": 8000,
        "stok": 20
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
